### ISSUE TITLE
SIMD

### ISSUE THREAD

**Issue by dy** [stackgl/glsl-transpiler#30]
Use [SIMD](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SIMD) for some parts of stdlib. Should make things faster, even maybe reasonable in some cases.

**Comment by turbo** [comment]
Hiho.

I'm currently thinking about a possible future upgrade to turbo.js (once overall compatibility is increased), incorporating this project to simplify the development. SIMD integration for JS fallback code would be one of the features I wouldn't like to miss in such a version.

What's the state of this project in terms of future development? Is it "alive" :-) ?

**Comment by dfcreative** [comment]
Hi @turbo!
Well all simple basic tests I can think of pass, there is a couple of complicated examples which just hang, I can’t figure out is it because of transpiler or complexity of the code itself.
I don’t have proper hardware to test SIMD, so that ticket is left up to contributors.
As for the state of the project - if you find any bugs I will try to fix them, otherwise I don’t see any strong reason for significant changes here, as far as it works it is good.

**Comment by seb776** [comment]
I think this issue can be closed as SIMD on browsers is no longer a subject :p as a side note, have you considered using glm-js for the math functions ?

**Comment by dy** [comment]
glm-js is cool reference, didn't know about that, but it's unlikely we'll use it here. Thanks!
